services:
  redis:
    image: redis:alpine
    container_name: fake-fintech_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  rabbitmq:
    container_name: fake-fintech_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/data
    networks:
      - laravel-network

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  laravel-network:
    driver: bridge