services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fake-fintech_backend
    restart: unless-stopped
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-example_db}
      DB_USERNAME: ${DB_USERNAME:-example_user}
      DB_PASSWORD: ${DB_PASSWORD:-example_password}
      CACHE_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_DRIVER: redis
      JWT_SECRET: ${JWT_SECRET:-FAKE_JWT_SECRET}
    depends_on:
      - mysql
      - redis
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: fake-fintech_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-example_db}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-example_password}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3333:3306"
    networks:
      - laravel-network

  redis:
    image: redis:alpine
    container_name: fake-fintech_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel-network

  fake_fintech_nginx_backend:
    image: nginx:stable-alpine
    container_name: fake_fintech_nginx_backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www:ro
      - ./nginx/nginx.backend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    networks:
      - laravel-network

  rabbitmq:
    container_name: fake-fintech_rabbitmq
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/data
    networks:
      - laravel-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-build
    container_name: fake-fintech_frontend
    image: fake-fintech_frontend:latest
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - laravel-network

volumes:
  mysql_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  laravel-network:
    driver: bridge