FROM node:20.11.1 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/coreui-free-angular-admin-template/browser/ /usr/share/nginx/html/
COPY default.conf /etc/nginx/conf.d/default.conf