# Stage 1: Build the application
FROM node:20.11.1 AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the application from nginx
FROM nginx:alpine
COPY --from=build /app/dist/call-center/browser /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf