name: Push-CI

on: push

jobs:
  linter:
    name: Lint Frontend Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter (Frontend Only)
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.KEY }}
          LINTER_RULES_PATH: './monolith/frontend'
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_ES: true
          FILTER_REGEX_EXCLUDE: (dist|node_modules|backend)